language: generic 
sudo: required
services:
    - docker
    
before_install:
    - docker build -t likeabosch/docker-react -f Dockerfile.dev .    

script:
    - docker run -e CI=true likeabosch/docker-react npm run test    